<?php

return [
    'evaluation_types'      => ['SKALA', 'HASIL KARYA', 'ANEKDOT'],
//    'evaluation_indicators' => ['BB', 'MB', 'BSH', 'BSB'],
    'evaluation_indicators' => ['BAIK', 'CUKUP', 'PERLU DILATIH'],
    'report_indicators'     => ['A', 'B', 'C'],
    'user_role'             => ['ADMIN', 'TEACHER', 'STUDENT', 'PARENT', 'GUEST'],
    'gender'                => ['Pria', 'Wanita'],
    'religion'              => ['ISLAM', 'KRISTEN', 'KATOLIK', 'BUDHA', 'HINDU', 'KONG HU CU'],
    'distance_from_home'    => [
        '+/- 1 KM',
        '+/- 5 KM',
        '+/- 10 KM',
        '+/- 50 KM',
        '> 100 KM',
    ],
    'time_from_home'        => [
        '< 10 Menit',
        '+/- 30 Menit',
        '+/- 1 Jam',
        '+/- 2 Jam',
        '> 2 Jam',
    ],
    'guards'                => ['AYAH', 'IBU', 'SAUDARA', 'KERABAT', 'LAINNYA'],
    'aspect_categories'     => [
        'NILAI-NILAI AGAMA DAN MORAL',
        'FISIK MOTORIK',
        'KOGNITIF',
        'BAHASA',
        'SOSIAL EMOSIONAL',
        'SENI',
    ],
    'aspect_subcategories'  => [
        'Motorik Kasar',
        'Motorik Halus',
        'Kesehatan dan Perilaku Keselamatan',
        'Belajar dan Pemecahan Masalah',
        'Berpikir Logis',
        'Berpikir Simbolik',
        'Memahami Bahasa',
        'Mengungkapkan Bahasa',
        'Keaksaraan',
        'Kesadaran Diri',
        'Rasa Tanggung jawab Diri Sendiri dan Orang lain',
        'Perilaku Prososial',
        'Anak mampu menikmati berbagai alunan lagu atau suara',
        'Tertarik dengan kegiatan seni',
    ],
    'result_assessments'    => ['BAIK', 'CUKUP', 'PERLU DILATIH']
];
